=== hongpham2299/RESTAssuredAutomationProject/src/test/resources/products/addProductSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "price": {
      "type": "number"
    },
    "discountPercentage": {
      "type": "number"
    },
    "rating": {
      "type": "number"
    },
    "stock": {
      "type": "integer"
    },
    "brand": {
      "type": "string"
    },
    "category": {
      "type": "string"
    },
    "thumbnail": {
      "type": "string"
    },
    "images": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    }
  }
}

=== hongpham2299/RESTAssuredAutomationProject/src/test/resources/products/addProduct.json
{
  "title":"Leather Watch",
  "description":"An Awesome Leather Watch",
  "price":765.41,
  "discountPercentage": 12.96,
  "rating":4.84,
  "stock":6,
  "brand":"Fossil",
  "category":"Beauty",
  "thumbnail":"https://i.dummyjson.com/data/products/101/thumbnail.jpg",
  "images": [
    "https://i.dummyjson.com/data/products/101/1.jpg",
    "https://i.dummyjson.com/data/products/101/2.jpg",
    "https://i.dummyjson.com/data/products/101/3.jpg",
    "https://i.dummyjson.com/data/products/101/4.jpg",
    "https://i.dummyjson.com/data/products/101/thumbnail.jpg"
  ]
}
